### ISSUE TITLE
force-dev-tool and latest version of api, say 41

### ISSUE THREAD

**Issue by okram999** [amtrack/force-dev-tool#100]
hi @amtrack - i know from various discussions that sf have changed the way they handle permSets while deploying from version 40 onwards. Does the tool (force-dev-tool) handle the latest versions say ver41 of the mdAPI?

**Comment by amtrack** [comment]
Not yet.
Do you want to start working on that?

**Comment by okram999** [comment]
it is just the permSets that have changed with the new api version?

**Comment by amtrack** [comment]
As far as I know, yes.

**Comment by ravirajah** [comment]
still stuck on api 45  how can we get this to be 47?

**Comment by amtrack** [comment]
The new PermissionSet behaviour was implemented in #208
