### ISSUE TITLE
Unable to generate package.xml file for multiple types (Profiles, WorkFlow, Assignment Rules, Permissionset, Labels, CustomObjects, Custom Labels)

### ISSUE THREAD

**Issue by nithyusha23** [amtrack/force-dev-tool#106]
We have modified few files in the following types and tried to generate package.xml file. However, it has generated an empty file as shown below and did not create create any types with the modified members in it.
?xml version="1.0" encoding="UTF-8"?
Package xmlns="http://soap.sforce.com/2006/04/metadata"
    version38.0/version
/Package

Types:
CustomObject
AssignmentRules
Workflow
PermissionSet
Profile
CustomLabel
Label

**Comment by amtrack** [comment]
@nithyusha23 Can you please share the steps to reproduce this issue?

**Comment by nithyusha23** [comment]
1. Added following line in src/workflows/AHRS_Settings__c.workflow
<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata"/>
2. Ran git diff 4bb8cf84 49df18b1 | force-dev-tool changeset create vat command
3. It gave following result
?xml version="1.0" encoding="UTF-8"?
Package xmlns="http://soap.sforce.com/2006/04/metadata"
version38.0/version
/Package

**Comment by amtrack** [comment]
* What version of force-dev-tool are you running (`force-dev-tool --version`)?
* Can you please share the (redacted) output of `git diff 4bb8cf84 49df18b1` in a markdown code block formatted as `diff`?

**Comment by nithyusha23** [comment]
I entered wrong sha code in earlier comment. Please see the correct details below:

C:\Users\Nithyusha_Gurujala1\Ipreotest>git diff 0249cecc 3f82c8a6
diff --git a/src/workflows/AHRS_Settings__c.workflow b/src/workflows/AHRS_Settings__c.workflow
index 256a3da..ace6510 100644
--- a/src/workflows/AHRS_Settings__c.workflow
+++ b/src/workflows/AHRS_Settings__c.workflow
@@ -1,3 +1,4 @@
 <?xml version="1.0" encoding="UTF-8"?>
+
 <Workflow xmlns="http://soap.sforce.com/2006/04/metadata"/>



C:\Users\Nithyusha_Gurujala1\Ipreotest>git diff 0249cecc 3f82c8a6 | force-dev-tool changeset create vat
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>

exported metadata container to config\deployments\vat

C:\Users\Nithyusha_Gurujala1\Ipreotest>force-dev-tool --version
1.0.0

**Comment by amtrack** [comment]
So the diff is only an added blank line?
Is there some content in `src/workflows/AHRS_Settings__c.workflow` at all?

**Comment by nithyusha23** [comment]
I have modified another file which has content:
`C:\Users\Nithyusha_Gurujala1\Ipreotest>git diff 3f82c8a6 ab78742d | force-dev-tool changeset create vat
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>`

`C:\Users\Nithyusha_Gurujala1\Ipreotest>git diff 3f82c8a6 ab78742d
diff --git a/src/permissionsets/Account_Management.permissionset b/src/permissionsets/Account_Management.permissionset
index afc8b83..c28161f 100644
--- a/src/permissionsets/Account_Management.permissionset
+++ b/src/permissionsets/Account_Management.permissionset
@@ -1,5 +1,6 @@
 <?xml version="1.0" encoding="UTF-8"?>
 
+
 <PermissionSet xmlns="http://soap.sforce.com/2006/04/metadata">
     <applicationVisibilities>
         <application>Attachments_and_Notes_migrator</application>`

It is not working for following types:
CustomObject
AssignmentRules
Workflow
PermissionSet
Profile
CustomLabel
Label

**Comment by amtrack** [comment]
@nithyusha23 , have you been able to solve this in the meantime?
