### ISSUE TITLE
Code Coverage and Code Review

### ISSUE THREAD

**Issue by nithyusha23** [amtrack/force-dev-tool#108]
I'd like to get a report similar to the one produced by Run Local Tests in the Force.com IDE but in HTML / Json on my local machine.

For the rest of our system we use Sonar http://www.sonarsource.org/ to produce the reports.
Do you know any best approach to achieve this?

In addition, we are using PMD tool for code review. any possibility to run PMD and get the result using this tool?

**Comment by amtrack** [comment]
@nithyusha23 ,

you might be better off running your tests with the official Salesforce DX CLI (sfdx).

Please see `sfdx forc:apex:test:run` and `sfdx force:apex:test:report` in the [docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_apex.htm#cli_reference_force_apex)
