### ISSUE TITLE
change set creation on Win

### ISSUE THREAD

**Issue by alexey-filippov** [amtrack/force-dev-tool#110]
the application is not working correctly for Win. 

Tried to create change sets for masked path: src/classes/*.cls but got the error:

![image](https://user-images.githubusercontent.com/35339939/34832446-0da9108a-f6fb-11e7-8f86-d08dfaac9aec.png)

**Comment by amtrack** [comment]
Hi @alexey-filippov ,

I'm not a Windows guy. Can you try the following please

```console
$ force-dev-tool changeset create -f depl src\classes\*.cls
```

**Comment by alexey-filippov** [comment]
no chance. the same results. also change set deployment also is not working 

`C:\workspace\git_workspace\sparc>force-dev-tool deploy -d=.\config\deployments\undo_2
Running Deployment of directory =.\config\deployments\undo_2 to remote myorg
Error: Deployment failed.
 - Error in file 'package.xml': No package.xml found`

**Comment by amtrack** [comment]
Filename expansion is a feature of your Terminal/Shell.
If you're using `cmd.exe` or `PowerShell` this seems not supported.

With `Git Bash` which should come with the default Git installation on Windows this works fine.

**Comment by alexey-filippov** [comment]
Yes, you are right. With Git Bash the change set creation working fine using git diff , but path with mask -nope, very slow
