### ISSUE TITLE
could you please specify the limitations / list the components that cannot be deployed by force-dev-tool? 

### ISSUE THREAD

**Issue by ranjitbalu** [amtrack/force-dev-tool#111]
could you please specify the limitations / list the components that cannot be deployed by force-dev-tool?

**Comment by amtrack** [comment]
Hi @ranjitbalu ,

if you have a directory or zip file prepared, `force-dev-tool` should be able to deploy anything that is supported by the Metadata API.

Are you referring to the `changeset create` command in order to create a deployable directory?

**Comment by lodossDev** [comment]
Hi, when using the changeset create command, what are the metadata components that are not supported by this tool. 

Also I am getting this error around the class meta xml files, which are not copied over:

Error completing missing metadata: classes/AccountAdminOffice.cls-meta.xml
Error completing missing metadata: classes/JobQueueService.cls-meta.xml
Error completing missing metadata: classes/JobWorker.cls-meta.xml
