### ISSUE TITLE
Package.xml is not capturing when we change <enableFeeds> value in objects

### ISSUE THREAD

**Issue by nithyusha23** [amtrack/force-dev-tool#112]
We have changed <enableFeeds>true</enableFeeds> value to <enableFeeds>false </enableFeeds> in objects and when executed package.xml, it did not identify the above change and created an empty xml file.

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>
`

**Comment by nithyusha23** [comment]
Anybody has seen this issue already. If yes, please let me know if you found any solution for this issue.

**Comment by amtrack** [comment]
Hi @nithyusha23 ,

yes i'm aware of this.

Related issues: #90, #13

**Comment by nithyusha23** [comment]
Could you please let us know if there are any other issues as such , so that we do not face any sudden surprises.

**Comment by amtrack** [comment]
duplicate of #90, #13
