### ISSUE TITLE
Force Dev Tools and Wave

### ISSUE THREAD

**Issue by neo2005** [amtrack/force-dev-tool#113]
Does Force-dev-tools have implemented the support for wave? Wave is a new tool. If not, are you planning to add it any time soon?

**Comment by amtrack** [comment]
Hi @neo2005 ,

unfortunately i have no experience with Wave.

What kind of support for Wave do you mean?

As far as i can see there are several Wave-related Metadata types listed in the
[Metadata API Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_waveapplication.htm).

In theory force-dev-tool should be able to retrieve/deploy those types.

Please let me know if you run into any bugs or missing functionality to do so.

**Comment by abd3** [comment]
Woo hoo!! Thanks for the review and for the quick merge @amtrack!
