### ISSUE TITLE
Add functionality to forceignore to include only specific ones and exclude others

### ISSUE THREAD

**Issue by rajruprai** [amtrack/force-dev-tool#114]
Hi,

One issue I am having is that .forceignore will exclude all of the metadata if, for example, I put "CustomField/*". However, there is no option to that will allow for include "CustomField/Account.somefield__c", but exclude all others. 

Is this possible?

**Comment by amtrack** [comment]
Hi @rajruprai ,
this is already possible:

```
# ignore all fields except CustomField/Account.somefield__c
CustomField/**/*
!CustomField/Account.somefield__c
```
