### ISSUE TITLE
Error git diff | force-dev-tool changeset create

### ISSUE THREAD

**Issue by rodolfonoviski** [amtrack/force-dev-tool#120]
C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\manifest.js:57
                        type: component.type,
                                       ^

TypeError: Cannot read property 'type' of null
    at module.exports.Manifest.add (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\manifest.js:57:19)
    at C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:321:43
    at Array.forEach (<anonymous>)
    at DestroyableTransform._transform (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:308:16)
    at DestroyableTransform.Transform._read (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:418:64)
    at writeOrBuffer (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_readable.js:619:20)

**Comment by leboff** [comment]
Hey @rodolfonoviski can you provide an example of a diff that causes this issue?

**Comment by rodolfonoviski** [comment]
@leboff 
 git diff origin/backupDiarioSTI Merge_STI_Vida_v1  | force-dev-tool changeset create vidaV1 -f


M       src/classes/BatchPartnerSurvey.cls
M       src/classes/BatchPartnerSurvey.cls-meta.xml
M       src/classes/BatchPartnerSurveyTest.cls-meta.xml
M       src/classes/BatchPartneySurvey.cls-meta.xml
M       src/classes/BatchPartneySurveyTest.cls-meta.xml
M       src/classes/CaseAndServRetencaoRestControllerTest.cls
M       src/classes/CaseAndServRetencaoRestituicaoController.cls
M       src/classes/CaseAndServiceBankValidationController.cls
M       src/classes/CaseServiceBankValidationControllerTest.cls
M       src/classes/IntegrationCancelEndorsementMock.cls
M       src/classes/LeadDAO.cls
M       src/classes/ObjectFactory.cls
M       src/classes/PartnerSurveyEmailService.cls-meta.xml
M       src/components/CaseAndServiceBankValidation.component
M       src/labels/CustomLabels.labels
M       "src/layouts/Protocolo__c-C\303\263pia de Layout de Protocolo - Criadores.layout"
M       "src/layouts/Protocolo__c-Layout de Protocolo - Opera\303\247\303\243o.layout"
M       src/layouts/Protocolo__c-Protocolo Layout.layout
M       src/objectTranslations/Account-pt_BR.objectTranslation
M       src/objectTranslations/Protocolo__c-pt_BR.objectTranslation
M       src/objects/Account.object
M       src/pages/CaseAndServiceRetencaoDadosBancarios.page
M       src/pages/Visao360Home.page

**Comment by rodolfonoviski** [comment]
Does anyone have any idea what it might be?

**Comment by amtrack** [comment]
Hi @rodolfonoviski ,

can you please check your version

```console
$ force-dev-tool --version
```

If that does not output `1.1.0` please try installing the latest stable version using

```console
$ npm install -g force-dev-tool
```

**Comment by rodolfonoviski** [comment]
Hi @amtrack It is at version 1.1.0

**Comment by amtrack** [comment]
Let's try to lock this error down to a specific Metadata Type:

```bash
for mdapiType in classes components layouts objectTranslations objects pages; do
    git diff origin/backupDiarioSTI Merge_STI_Vida_v1 -- "${mdapiType}" | force-dev-tool changeset create "vidaV1-${mdapiType}" -f;
done
```

**Comment by rodolfonoviski** [comment]
$ for mdapiType in classes components layouts objectTranslations objects pages; do
>     git diff origin/backupDiarioSTI Merge_STI_Vida_v1 -- "${mdapiType}" | force-dev-tool changeset create "vidaV1-${mdapiType}" -f;
> done
Error completing missing metadata: classes\AdmAnaliseConformidadeDAO.cls-meta.xml
Error completing missing metadata: classes\BatchAnaliseDeConformidadeRule.cls-meta.xml
Error completing missing metadata: classes\BatchAnaliseDeConformidadeRuleTest.cls-meta.xml
Error completing missing metadata: classes\BatchAnaliseDeConformidades.cls-meta.xml
Error completing missing metadata: classes\BatchAnaliseDeConformidadesTest.cls-meta.xml
Error completing missing metadata: classes\BatchPartneySurvey.cls
Error completing missing metadata: classes\BatchPartneySurveyTest.cls
Error completing missing metadata: classes\CaseTriggerHandler.cls-meta.xml
Error completing missing metadata: classes\LeadDAO.cls-meta.xml
Error completing missing metadata: classes\LiveChatTranscriptTriggerHandler.cls-meta.xml
Error completing missing metadata: classes\ObjectFactoryTest.cls-meta.xml
Error completing missing metadata: classes\PartnerSurveyEmailService.cls-meta.xml
Error completing missing metadata: classes\TestSetup.cls-meta.xml
Error completing missing metadata: classes\Util.cls-meta.xml
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AdmAnaliseConformidadeDAO</members>
        <members>BatchAnaliseDeConformidadeRule</members>
        <members>BatchAnaliseDeConformidadeRuleTest</members>
        <members>BatchAnaliseDeConformidades</members>
        <members>BatchAnaliseDeConformidadesTest</members>
        <members>BatchPartneySurvey</members>
        <members>BatchPartneySurveyTest</members>
        <members>CaseTriggerHandler</members>
        <members>LeadDAO</members>
        <members>LiveChatTranscriptTriggerHandler</members>
        <members>ObjectFactoryTest</members>
        <members>PartnerSurveyEmailService</members>
        <members>TestSetup</members>
        <members>Util</members>
        <name>ApexClass</name>
    </types>
    <version>41.0</version>
</Package>

Destructive Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AnaliseConformidadeTriggerHandler</members>
        <members>AnaliseConformidadeTriggerHandlerTest</members>
        <members>BatchUpdateAllCaseTask</members>
        <members>BatchUpdateAllLiveChatTranscript</members>
        <members>BatchUpdateAllProtocols</members>
        <members>BatchUpdateAllUserServicePresence</members>
        <members>BatchUpdateCaseDurationSeconds</members>
        <members>BatchUpdateLiveAgentSession</members>
        <members>CaseTaskTriggerHandler</members>
        <members>LiveAgentSessionTriggerHandler</members>
        <members>ProtocoloTriggerHandler</members>
        <members>QueueDAO</members>
        <members>ResponsavelBUDAO</members>
        <members>UserServicePresenceTriggerHandler</members>
        <name>ApexClass</name>
    </types>
</Package>

exported metadata container to ..\config\deployments\vidaV1-classes
Error completing missing metadata: components\CaseAndServiceHighlightPainel.component-meta.xml
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>CaseAndServiceHighlightPainel</members>
        <name>ApexComponent</name>
    </types>
    <version>41.0</version>
</Package>

exported metadata container to ..\config\deployments\vidaV1-components
C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\manifest.js:57
                        type: component.type,
                                       ^

TypeError: Cannot read property 'type' of null
    at module.exports.Manifest.add (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\manifest.js:57:19)
    at C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:321:43
    at Array.forEach (<anonymous>)
    at DestroyableTransform._transform (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:308:16)
    at DestroyableTransform.Transform._read (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:418:64)
    at writeOrBuffer (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_readable.js:619:20)
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account-pt_BR</members>
        <members>Administracao_de_Analise_de_Conformidade__c-en_US</members>
        <members>Case-en_US</members>
        <members>Case-pt_BR</members>
        <members>Case_Task__c-en_US</members>
        <members>Case_Task__c-pt_BR</members>
        <members>LiveChatTranscript-pt_BR</members>
        <members>Protocolo__c-en_US</members>
        <members>Protocolo__c-pt_BR</members>
        <name>CustomObjectTranslation</name>
    </types>
    <version>41.0</version>
</Package>

Destructive Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Responsavel_da_BU__c-en_US</members>
        <name>CustomObjectTranslation</name>
    </types>
</Package>

exported metadata container to ..\config\deployments\vidaV1-objectTranslations
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>LiveAgentSession.Duracao_media_de_atendimentos_em_horas__c</members>
        <members>LiveAgentSession.Tempo_Ausente__c</members>
        <members>LiveAgentSession.Tempo_Ocioso__c</members>
        <members>LiveAgentSession.Tempo_Online__c</members>
        <members>LiveAgentSession.Tempo_gasto_nos_bate_papos__c</members>
        <members>LiveAgentSession.Tempo_na_Capacidade_Maxima__c</members>
        <members>LiveChatTranscript.Abandoned_after_in_hours__c</members>
        <members>LiveChatTranscript.Duracao_do_bate_papo_em_horas__c</members>
        <members>LiveChatTranscript.Tempo_de_espera_em_horas__c</members>
        <members>LiveChatTranscript.Tempo_medio_de_resposta_do_operador__c</members>
        <members>LiveChatTranscript.Tempo_medio_de_resposta_do_visitante__c</members>
        <members>UserServicePresence.Duracao_do_status_em_horas__c</members>
        <members>UserServicePresence.Tempo_efetivo_em_pausa_em_horas__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Account.Account_Speaker</members>
        <name>FieldSet</name>
    </types>
    <types>
        <members>Case.Campos_Obrigatorios_Business_Account</members>
        <members>Case.Contact_Phone_com_numeros_apenas</members>
        <members>Case.Lookup_Account_Prospect_Partner</members>
        <members>Case.NotChangeCanceledCase</members>
        <members>Case.Status_changed</members>
        <members>Case.Validacao_de_Assunto</members>
        <name>ValidationRule</name>
    </types>
    <version>41.0</version>
</Package>

Destructive Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Administracao_de_Analise_de_Conformidade__c.Manager_acionado__c</members>
        <members>Case.Case_Duration_in_Seconds_Time_Text__c</members>
        <members>Case.Speaker_Email__c</members>
        <members>Case.Speaker_ID__c</members>
        <members>Case.Speaker_Name__c</members>
        <members>Case_Task__c.Case_Number__c</members>
        <members>Case_Task__c.Data_resolucao_da_solicitacao__c</members>
        <members>Case_Task__c.Feedback__c</members>
        <members>Case_Task__c.Prazo_de_atendimento_da_solicitacao__c</members>
        <members>Case_Task__c.SLA_exceeded__c</members>
        <members>Case_Task__c.Task_Duration_in_Seconds_Time_Text__c</members>
        <members>LiveAgentSession.Tempo_Gasto_nos_bate_papos__c</members>
        <members>Protocolo__c.Protocol_Duration_Time_Text__c</members>
        <members>UserServicePresence.AtCapacityDuration_Time_Text__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Responsavel_da_BU__c</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>Case_Task__c.AUTO_Analise_de_Conformidade_Case_Task</members>
        <members>Case_Task__c.CAP_Analise_de_Conformidade_Case_Task</members>
        <members>Case_Task__c.CONS_Analise_de_Conformidade_Case_Task</members>
        <members>Case_Task__c.HAB_Analise_de_Conformidade_Case_Task</members>
        <members>Case_Task__c.PREST_Analise_de_Conformidade_Case_Task</members>
        <members>Case_Task__c.PREV_Analise_de_Conformidade_Case_Task</members>
        <members>Case_Task__c.RD_Analise_de_Conformidade_Case_Task</members>
        <members>Case_Task__c.VIDA_An_lise_de_Conformidade_Case_Task</members>
        <name>ListView</name>
    </types>
    <types>
        <members>Case_Task__c.Fechamento_da_Tarefa</members>
        <name>ValidationRule</name>
    </types>
</Package>

exported metadata container to ..\config\deployments\vidaV1-objects
Error completing missing metadata: pages\CaseAndServiceRetencaoDadosBancarios.page-meta.xml
Error completing missing metadata: pages\HighLightPanel.page-meta.xml
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>CaseAndServiceRetencaoDadosBancarios</members>
        <members>HighLightPanel</members>
        <name>ApexPage</name>
    </types>
    <version>41.0</version>
</Package>

exported metadata container to ..\config\deployments\vidaV1-pages

**Comment by amtrack** [comment]
I'm guessing `layouts` failing due to special characters in the file names.
Regarding `classes` and `pages` i have no clue however.

**Comment by amtrack** [comment]
Are you using Git Bash?

**Comment by rodolfonoviski** [comment]
@amtrack Yes

**Comment by amtrack** [comment]
Hmm, unfortunately i don't know if i can help you any further without getting my hands on.

Ideally you could create a repository with a minimal example to reproduce this error.
In general `force-dev-tool` should be running on Windows according to the [AppVeyor builds](https://ci.appveyor.com/project/amtrack/force-dev-tool/branch/master).
So it would be great to find out what's wrong here.

**Comment by rodolfonoviski** [comment]
@amtrack I can create a private repository and share it with you, so we can see what went wrong.

**Comment by amtrack** [comment]
@rodolfonoviski sounds OK to me.

**Comment by leboff** [comment]
The fix from #123 might work here as well..

**Comment by dieffrei** [comment]
It is related to layout special chars;
Take a look on #123 ;)

PT-BR: Esse erro acontecia comigo direto, só desativar o quotepath

**Comment by amtrack** [comment]
@rodolfonoviski did the trick from #123 work for you?

**Comment by amtrack** [comment]
@rodolfonoviski are you running the commands from your project root directory or from inside of the `src` directory?

I just spotted the relative part `..\`  of the path in your output:
`exported metadata container to ..\config\deployments\vidaV1-pages`

Please see my answer in #124 which might be related to your issue.
