### ISSUE TITLE
Custom Object not retaining label name

### ISSUE THREAD

**Issue by lodossDev** [amtrack/force-dev-tool#121]
Hi, when a custom object is detected from a change-set diff, It does not add the label element, causing the error "Must specific a non-empty label for Custom Object"

I think it only needs to retain other things, name field etc..

**Comment by okram999** [comment]
@lodossDev - why did you close this? was this resolved?

**Comment by okram999** [comment]
@amtrack  - do you think this is a bug in SF? So we have a custom obj and to that a weblink was added. Git diff saw the change. and force-dev-tool, created the before

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
      <actionName>Edit</actionName>
      <type>Default</type>
    </actionOverrides>
    <webLinks>
      <fullName>EditVF</fullName>
      <availability>online</availability>
      <displayType>button</displayType>
      <height>600</height>
      <linkType>page</linkType>
      <masterLabel>Edit</masterLabel>
      <openType>noSidebar</openType>
      <page>PropertyRedirect</page>
      <protected>false</protected>
    </webLinks>
</CustomObject>
```
But salesforce deployment - fails with the` "Must specific a non-empty label for Custom Object"`

any thoughts?

**Comment by lodossDev** [comment]
I think this was an issue with my global diff. 

What I remember if you deploy a custom object, you have to specify the custom object label and name field.

**Comment by lodossDev** [comment]
On another note, is there anyway to generate or output the test classes for a changeset?
What I am trying to do is to run only test classes for a changeset.

**Comment by okram999** [comment]
in order to get the deployment (partial), work. i have to manually add all the missing pieces into the one that the tool generated.

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
      <actionName>Edit</actionName>
      <type>Default</type>
    </actionOverrides>
	<label>Apple</label>
	<pluralLabel>Apples</pluralLabel>
	<nameField>
        <label>Apple Name</label>
        <trackFeedHistory>false</trackFeedHistory>
        <trackHistory>true</trackHistory>
        <type>Text</type>
    </nameField>
	<deploymentStatus>Deployed</deploymentStatus>
	<sharingModel>Private</sharingModel>
    <webLinks>
      <fullName>EditVF</fullName>
      <availability>online</availability>
      <displayType>button</displayType>
      <height>600</height>
      <linkType>page</linkType>
      <masterLabel>Edit</masterLabel>
      <openType>noSidebar</openType>
      <page>PropertyRedirect</page>
      <protected>false</protected>
    </webLinks>
</CustomObject>
```

**Comment by okram999** [comment]
> On another note, is there anyway to generate or output the test classes for a changeset?
> What I am trying to do is to run only test classes for a changeset.


Although i think this is not the right thread. I would think that there is no feature yet. But that can be done, by tweaking the ant migration tool's task. And some discipline with the the naming of the test classes

Please do not post anything further for this in this thread.
