### ISSUE TITLE
Missing meta-xml files

### ISSUE THREAD

**Issue by lodossDev** [amtrack/force-dev-tool#122]
log:

Error completing missing metadata: classes/ContactHandler.cls
Error completing missing metadata: classes/ContactHandler.cls-meta.xml
Error completing missing metadata: classes/LeadContacts.cls
Error completing missing metadata: classes/LeadContacts.cls-meta.xml

I am getting these errors on ApexClasses and some have missing meta.xml files?

**Comment by amtrack** [comment]
Can you please provide the command you used to generate the changeset?

**Comment by lodossDev** [comment]
This is the command I am using:

git diff %sf.post_branch% %sf.target_branch% -- src/ | force-dev-tool changeset create package_build

I have specified to only check src directory for diff and now it works.

**Comment by amtrack** [comment]
I see. Are there any other directories in your repository which are named `src`.
I'm wondering why `force-dev-tool` is getting confused.
