### ISSUE TITLE
Layout name with special chars bug on change set generation

### ISSUE THREAD

**Issue by dieffrei** [amtrack/force-dev-tool#123]
When I try to create a change set:
git diff master | force-dev-tool change set create feature-merge -f

I got some errors for all layout names that have using special chars:
Given example:
**Correct name:** AccountAreaSales__c-Layout de Área de venda.layout
**Wrong name after on change set:** AccountAreaSales__c-Layout de \303\201rea de venda.layout"

Another strange thing is after execution, was created two change sets: **feature-merge** and **"b**

**Comment by leboff** [comment]
@dieffrei can you set core.quotepath to off before running the diff and see if that helps?

`git config core.quotepath off`

**Comment by dieffrei** [comment]
Thank you @leboff that's it!
Much appreciated your help!
