### ISSUE TITLE
missing "--no-destructive" on create changeset

### ISSUE THREAD

**Issue by pelim** [amtrack/force-dev-tool#125]
im missing the a option to create a change set without the destructive changes

**Comment by amtrack** [comment]
Hi @pelim 
i'm not planning to implement this because i believe this is not the intention of the `changeset` command.
However i suggest that you simply delete the `destructiveChanges.xml` file afterwards:

```console
$ git diff ... | force-dev-tool changeset create foo && rm -f config/deployments/foo/destructiveChanges.xml
```
