### ISSUE TITLE
Change set deployment process

### ISSUE THREAD

**Issue by sheldonleelazarus** [amtrack/force-dev-tool#129]
Hi Amtrack

Currently the way force-dev-tool deploys using change set is : If there are destructive changes in a changeset the force-dev-tool will proceed with destructive changes first and then proceed with the actual deploy,

I have a quick question how can I set my destructive changes to happen after my actual deploy using force-dev-tool?

**Comment by amtrack** [comment]
Quoting the [docs](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_destructive_changes.htm)
> To delete components after adding or updating other components, create a manifest file that’s named destructiveChangesPost.xml and include the components to delete.

So you just have to rename `destructiveChanges.xml` to `destructiveChangesPost.xml`.

**Comment by sheldonleelazarus** [comment]
Hi

Is there a way to automate it?

Kind Regards
Sheldon Lazarus

**Comment by amtrack** [comment]
@sheldonleelazarus Well, there is no flag in `force-dev-tool` itself yet.
However you could just use unix commands, for example

```console
$ git diff develop feature/foo | force-dev-tool changeset create foo && mv config/deployments/foo/destructiveChanges.xml config/deployments/foo/destructiveChangesPost.xml
```

**Comment by sheldonleelazarus** [comment]
Thanks so much will use this
