### ISSUE TITLE
changeset create: handle properties of complex Metadata Types (e.g. CustomObject)

### ISSUE THREAD

**Issue by amtrack** [amtrack/force-dev-tool#13]
Handling changes in named children of complex Metadata Types is already supported (changes in a `CustomField` within a `CustomObject`).
However changes in properties of its own Metadata Type aren't supported yet (e.g. `searchLayouts` of a `CustomObject`).

The approach should be as @froucher drafted:

```gherkin
Given we create a change set with force-dev-tool
When a list of independent child is added/modified
Then it will create a change set with the list of independent "component" 
 And excluding any metadata of the parent metadata

Given we create a change set with force-dev-tool
When a list property that doesn't belong to an independent child is added/modified
Then it will create a change set with the all "metadata" 
 And excluding all independent child metadata

Given we create a change set with force-dev-tool
When a list of independent child is added/modified
 And a list property that doesn't belong to an independent child is added/modified
Then it will create a independent "component" with the property value
 And it will create a change set with the all "metadata" 
```

Looking at the code, I think most of the changes could be applied in [metadata-file-container.js](https://github.com/amtrack/force-dev-tool/blob/2cb37b9bc7e89d17f033288a1ce87d9f4c3363aa/lib/metadata-file-container.js) (`parse`, `diff`, `toString`).

**Comment by froucher** [comment]
Hello,

Then I will start with this PR.

Sorry but I think I found some issues in the behaviours definition:

```gherkin
Given we create a change set with force-dev-tool
When a list of independent child is added/modified
Then it will create a change set with the list of independent "component" 
 And excluding any metadata of the parent metadata

Given we create a change set with force-dev-tool
When a list of parent properties that doesn't belong to an independent child is added/modified/removed
Then it will create a change set with the all parent metadata
 And excluding all independent child metadata

Given we create a change set with force-dev-tool
When a list of independent child is added/modified
 And a list of parent properties that doesn't belong to an independent child is added/modified
Then it will create a change set with the all parent metadata
 And it will create a change set with the list of independent "component" 
```

Right now, I am not sure about which must be the behaviour when some independent child is removed. @amtrack can you help me defining which is the expected behaviour?

Thanks and regards

**Comment by froucher** [comment]
Hi again,

Maybe the behaviour with a removed child is: 

```gherkin
Given a list of independent child has been removed in the git repository
 When a user launches this change set with force-dev-tool
 Then it will create a destructive change with the list of independent "component"
```

Thanks

**Comment by amtrack** [comment]
@froucher your last comment seems to be correct.

BTW creating a destructiveChanges.xml for e.g. a CustomField is already implemented: https://github.com/amtrack/sfdx-playground/tree/objects/config/deployments/expected

**Comment by froucher** [comment]
ok, thanks, I will keep you informed with the progress of the PR

**Comment by amtrack** [comment]
Thank you!

**Comment by froucher** [comment]
This is the PR #230 that we are working

**Comment by froucher** [comment]
Hello @amtrack, I am working to develop Compact Layout changes.

The PR #230, right now, works fine, it deploys right the changeset with new compact Layout.

The issue is with the destructiveChange.xml, compactLayout need to considered as a different component as the parent object to be removed.

This means that the solution need to consider CompactLayout as parent metadata when it is new or modification, but when it is removed it needs to be consider as a child component.

Do you agree with this?

Thanks

**Comment by amtrack** [comment]
@froucher I think CompactLayout can be treated as a named (standalone) metadata type.
I've adjusted the test. Please cherry-pick the commit if you agree: https://github.com/amtrack/force-dev-tool/commit/72c2bca26b70dd90dcf35326c613ae5f0084cb7d

**Comment by froucher** [comment]
Hello @amtrack,

This is related to the issue #226, which talks about Compact Layout deployment and how it depends on 'label' property. We thought that the way to resolve this is that compact Layout was not treated as a named metadata.

Now, maybe we need to think about other solution.

Do you agree?

Thanks

**Comment by amtrack** [comment]
So the initial assumption about `CompactLayout` was wrong but we now know that `CompactLayout` can be treated similar to `CustomField` as an independent and named child type.

**Comment by froucher** [comment]
Yes, you are right, thanks, I have checked your commit with Compact Layout test and it is an independent child, I do a rollback of the related changes, and I will fix that currently force-dev-tool creates a wrong `package.xml`:

```diff
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
-        <members>CustomObjectTest__c</members>
-        <name>CustomObject</name>
+        <members>CustomObjectTest__c.compactLayoutTest</members>
+        <name>CompactLayout</name>
    </types>
    <version>46.0</version>
</Package>
```

CustomObject changeset:

```diff
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
-    <allowInChatterGroups>false</allowInChatterGroups>
-    <compactLayoutAssignment>SYSTEM</compactLayoutAssignment>
      <compactLayouts>
          <fullName>compactLayoutTest</fullName>
          <fields>CreatedById</fields>
@@ -10,23 +8,4 @@
          <fields>OwnerId</fields>
          <label>compactLayoutTest</label>
     </compactLayouts>
-    <deploymentStatus>Deployed</deploymentStatus>
-    <enableActivities>false</enableActivities>
-    <enableBulkApi>true</enableBulkApi>
-    <enableFeeds>false</enableFeeds>
-    <enableHistory>false</enableHistory>
-    <enableLicensing>false</enableLicensing>
-    <enableReports>false</enableReports>
-    <enableSearch>true</enableSearch>
-    <enableSharing>true</enableSharing>
-    <enableStreamingApi>true</enableStreamingApi>
-    <label>CustomObjectTest</label>
-    <nameField>
-        <label>CustomObjectTest Name</label>
-        <type>Text</type>
-    </nameField>
-    <pluralLabel>CustomObjectTest</pluralLabel>
-    <searchLayouts/>
-    <sharingModel>ReadWrite</sharingModel>
-    <visibility>Public</visibility>
</CustomObject>
```

**Comment by froucher** [comment]
Hello @amtrack,

It seems it was very easy to resolve "Compact Layout" fix.

Please check the 723f8bdd611adea84e4bb218449ef390d30e83d5 commit, I have added "isNamed: true" in the "lib/describe-metadata-service.js". Is it right?

Thanks

**Comment by froucher** [comment]
About`SearchLayouts`, it is working, I have added two tests in the following commit a228d8c4c33b6c2157f5c676e5022f16ae693e16
