### ISSUE TITLE
Get the "Last modified by" for any metadata

### ISSUE THREAD

**Issue by okram999** [amtrack/force-dev-tool#130]
This is more of a question, and NOT an issue. 

@amtrack Is there a provision to get the "Last modified by" information for any metadata type in force-dev-tool?

**Comment by amtrack** [comment]
@okram999 
Sure!

Assuming that your remote is named `dev`.

fetch the state (if not already recently run)
```console
$ force-dev-tool fetch dev
```

show a list of metadata components if you're unsure
```console
$ force-dev-tool info list dev
ApexClass/ChangePasswordController
ApexClass/ChangePasswordControllerTest
...
```

now show information about a specific metadata component (here: `ApexClass/ChangePasswordController`). Note that this command accepts multiple component names or patterns. Thats why the resulting JSON is an array!

```console
$ force-dev-tool info show dev ApexClass/ChangePasswordController
[
  {
    "createdById": "005d0000001HnbXAAS",
    "createdByName": "John Doe",
    "createdDate": "2017-03-31T09:02:54.000Z",
    "fileName": "classes/ChangePasswordController.cls",
    "fullName": "ChangePasswordController",
    "id": "01p0W000003fHJ2QAM",
    "lastModifiedById": "005d0000001HnbXAAS",
    "lastModifiedByName": "John Doe",
    "lastModifiedDate": "2017-03-31T09:02:54.000Z",
    "manageableState": "unmanaged",
    "type": "ApexClass"
  }
]
```

If you have [jq](https://stedolan.github.io/jq/) installed, you can pipe this output to select only the `lastModifiedDate` property of the first element in the array

```console
$ force-dev-tool info show dev ApexClass/ChangePasswordController | jq -r '.[0].lastModifiedDate'
2017-03-31T09:02:54.000Z
```

**Comment by okram999** [comment]
@amtrack - awesome! , i will check it out.

**Comment by okram999** [comment]
the command works fine. Can we use the complete JSON file/object? 
Something like  `force-dev-tool info show spr18dev *`.   This will open another door to get the file names changed by specific users.

**Comment by amtrack** [comment]
@okram999

`*` won’t match any component and it should also be single quoted to prevent bash globbing.

This might work

```console
$ force-dev-tool info show dev '**/*'
```

or alternatively `'*/*' '*/*/*'`

**Comment by okram999** [comment]
Been playing with this https://github.com/shaphu/getFileMetaInfo

**Comment by okram999** [comment]
oh, @amtrack - i just realized that the `json `was already in  the `config `folder. 
I was under an impression that it was doing an `API `call to the `remote`.
