### ISSUE TITLE
Problem with force-dev-tool changeset with cli arguments

### ISSUE THREAD

**Issue by Nazareena** [amtrack/force-dev-tool#131]
When trying force-dev-tool changeset with cli arguments having custom field metadata the package build the complete Account object rather than having only the field, do we have any fix for this example command is as below
force-dev-tool changeset create vat src/pages/AccountExtensionVAT.page CustomField/Account.VAT__c

Deployment getting below error because package.xml has only the custom field Account.VAT__c but Account.object file has all metadata of the all the Account fields.
All Component Failures:

    objects/Account.object (Account.AccountNumber) -- Error: Not in package.xml
    objects/Account.object (Account.Active__c) -- Error: Not in package.xml
    objects/Account.object (Account.AnnualRevenue) -- Error: Not in package.xml
    objects/Account.object (Account.BillingAddress) -- Error: Not in package.xml
    objects/Account.object (Account.CustomerPriority__c) -- Error: Not in package.xml

**Comment by amtrack** [comment]
@Nazareena That's hard to tell.
Can you please provide the following information?

```console
$ force-dev-tool --version
$ force-dev-tool package version
$ tree -L 2 src
$ tree config/deployments/vat
```

**Comment by Nazareena** [comment]
$ force-dev-tool --version
1.1.1
$ force-dev-tool package version
36.0
$ tree -L 2 src
Too many parameters - 2
$ tree config/deployments/vat
Folder PATH listing for volume Windows
Volume serial number is 00000001 104C:6949
C:\SALESFORCEGARAGE\GITREPO\JENKINSTESTPROJECT\CONFIG\DEPLOYMENTS\VAT
├───classes
└───objects

Please find the response of the commands you have asked.

Deployment getting error because package.xml has only the custom field Account.VAT__c but Account.object file has all metadata of the all the Account fields.

Thanks for the support.

**Comment by Nazareena** [comment]
Please let us know any updates on this issue

**Comment by amtrack** [comment]
@Nazareena It seems strange to me that your directory `config/deployments/vat` contains `classes` and `objects` although you were trying to process a vf **page** and a custom field.

Can you please rerun the command with the `—force` flag to overwrite the generated directory:

```console
$ force-dev-tool changeset create -f vat src/pages/AccountExtensionVAT.page CustomField/Account.VAT__c
```

Also please try to use only expressions rather than paths like this

```console
$ force-dev-tool changeset create -f vat ApexPage/AccountExtensionVAT CustomField/Account.VAT__c
```

Further you could play a bit wit the command leaving out the page or the field etc to find out where it fails...

**Comment by Nazareena** [comment]
Sorry the comment i just pasted wrongly the actual comment i was trying was 
force-dev-tool changeset create vat src/classes/CreateOpportunity.cls CustomField/Account.QBO_Customer_test__c

and it is giving me the below package.xml
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>CreateOpportunity</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>Account.QBO_Customer_test__c</members>
        <name>CustomField</name>
    </types>
    <version>36.0</version>
</Package>

exported metadata container to config\deployments\vat

and the object folder contains entire Account.object with all the fields of the account object but I am expecting only the field Account.Account.QBO_Customer_test__c mentioned in the command above.


Please note when we use git diff --no-renames origin/master dev |  force-dev-tool changeset create vat 
its giving me the object folder with Account.object only the changed field.

**Comment by Nazareena** [comment]
Please let me know any updates on this issue

**Comment by amtrack** [comment]
@Nazareena can you provide a minimal working example (git repository) so that i can reproduce this?

**Comment by Nazareena** [comment]
used the below command for execution
force-dev-tool changeset create vat CustomField/QBO_Invoice_Line_Item__c.QBO_Unit_Price1__c
[TestProject.zip](https://github.com/amtrack/force-dev-tool/files/2149759/TestProject.zip)

Pls refer the config folder for the issue the package.xml has only field but the entire custom object is copied under the config object folder.

**Comment by amtrack** [comment]
@Nazareena I'm now able to reproduce your issue and working on a fix.

**Comment by Nazareena** [comment]
Working fine thanks.
