### ISSUE TITLE
When a permission set is updated in repository and based on that change a package is created label is missing

### ISSUE THREAD

**Issue by Stepan007** [amtrack/force-dev-tool#137]
When a permission set is updated in repository and based on that change a package is created label is missing.
During the deployment we get the following error
- Error in PermissionSet component '<PermissionSetName>': Required field is missing: label

**Comment by amtrack** [comment]
@Stepan007 that's right!
PermissionSets are not handled correctly at the moment.
I didn't have time so far to tackle this.
