### ISSUE TITLE
.forceignore doesn't ignore with create changeset

### ISSUE THREAD

**Issue by froucher** [amtrack/force-dev-tool#143]
With sfdx ".forceignore" works with the command "force:source:convert", but with "force-dev-tool create changeset" the content of ".forceignore" is not ignored.

Could this issue has sense? If yes, maybe at the end of next month I could make a PR.

**Comment by Stepan007** [comment]
I think .forceignore in case of force-dev-tool works for "force-dev-tool fetch" only, correct me if I'm wrong.

**Comment by amtrack** [comment]
@froucher , @Stepan007
The `.forceignore` file is currently being used in the `package` command and optionally in the `fetch` command (using `--use-forceignore`).
Yes, i would accept a PR adding this functionality to the `changeset` command.

**Comment by Nazareena** [comment]
Please let us know when forceignore functionality gets added to changeset command

**Comment by g1b3r** [comment]
Hello 

Can you please let me know when this functionality will be available to use. Or maybe someone have better version how to exclude something from deployment ? 

BR

**Comment by amtrack** [comment]
It is possible to [exclude files using git](https://stackoverflow.com/questions/5685007/making-git-log-ignore-changes-for-certain-paths/21079437#21079437).

Closing this issue as wontfix.
