### ISSUE TITLE
For two profiles, same diff, only one of the profiles are included into the package

### ISSUE THREAD

**Issue by Stepan007** [amtrack/force-dev-tool#152]
force-dev-tool changeset create "<package-name>" the following package is generated.
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Contact Centre Agent</members>
        <name>Profile</name>
    </types>
    <version>41.0</version>
</Package>

The diff result looks like this:

diff --git a/src/profiles/Contact Centre Agent.profile b/src/profiles/Contact Centre Agent.profile
index 4221c81ce..bf2b87fc9 100644
--- a/src/profiles/Contact Centre Agent.profile
+++ b/src/profiles/Contact Centre Agent.profile
@@ -11018,6 +11018,10 @@
         <apexPage>AnswersHome</apexPage>
         <enabled>true</enabled>
     </pageAccesses>
+    <pageAccesses>
+        <apexPage>PackageBuilderPhoneLedVF</apexPage>
+        <enabled>true</enabled>
+    </pageAccesses>
     <pageAccesses>
         <apexPage>BandwidthExceeded</apexPage>
         <enabled>true</enabled>
diff --git a/src/profiles/In-Direct Agent.profile b/src/profiles/In-Direct Agent.profile
index a22bfd524..4099cbd4e 100644
--- a/src/profiles/In-Direct Agent.profile
+++ b/src/profiles/In-Direct Agent.profile
@@ -11069,6 +11069,10 @@
         <apexPage>AnswersHome</apexPage>
         <enabled>true</enabled>
     </pageAccesses>
+    <pageAccesses>
+        <apexPage>PackageBuilderPhoneLedVF</apexPage>
+        <enabled>true</enabled>
+    </pageAccesses>
     <pageAccesses>
         <apexPage>BandwidthExceeded</apexPage>
         <enabled>true</enabled>

**Comment by amtrack** [comment]
@Stepan007 this sounds strange! Can you provide a minimal working example (git repository) so that i'm able to reproduce this?
