### ISSUE TITLE
force-dev-tool login mydev throws always invalid eventhough the valid credentials are given

### ISSUE THREAD

**Issue by Nazareena** [amtrack/force-dev-tool#158]
HI

Just tried these steps

$ force-dev-tool remote add mydev <username> <passwordsecuritytoken> --default
$ force-dev-tool remote add build <username> <passwordsecuritytoken>
$ force-dev-tool remote add production <username> <passwordsecuritytoken> https://login.salesforce.com
$ force-dev-tool login mydev

foce-dev-tool test

It always throws error as follows eventhough Iam giving proper credentials 

Error: Login failed for remote mydev: Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out.

Please help to solve this issue

**Comment by amtrack** [comment]
@Nazareena Please use Markdown to format your issues and issue comments in the future!

**Comment by Nazareena** [comment]
Its not working , do I am missing any steps here , pls send in detail steps.Thanks for the support.
force-dev-tool remote add mydev devopstarget@ibm.com 'passwordsecuritytoken' -u https://login.salesforce.com --default

force-dev-tool login
Error: Login failed for remote mydev: Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out.

**Comment by amtrack** [comment]
@Nazareena 
I'm closing this issue as i cannot reproduce this.
Have you tried using another tool that requires password and security token?
If you can verify that it works with e.g. [Ant Migration Tool](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/meta_development.htm) and it doesn't work with `force-dev-tool`, please re-open this issue.

**Comment by Nazareena** [comment]
tried in another tool where password and security token required and it worked , will be helpful if you can resolve this issue sharing even the password details 
force-dev-tool remote add mydev 'gfk-target-devorg@ibm.com' 'gfktarget1@ulDNnBiBilV5HyeDMDO9MwLt' -u https://login.salesforce.com --default

**Comment by amtrack** [comment]
@Nazareena 

The following works for me (don't quote the username):

```console
$ force-dev-tool remote add mydev gfk-target-devorg@ibm.com 'gfktarget1@ulDNnBiBilV5HyeDMDO9MwLt' -u https://login.salesforce.com --default
```

I left you a note as prove: https://ap4.salesforce.com/0666F000008Gt65
