### ISSUE TITLE
Issue while fetching the updates

### ISSUE THREAD

**Issue by kaulonline** [amtrack/force-dev-tool#161]
Hello Folks,

I followed the documentation and while fetching I am getting the below error 

force-dev-tool fetch --progress
Fetching from remote <orgname>
API Versions
Available Metadata Types
Folders
Metadata Components
**Error: [orgname]: sf:UNKNOWN_EXCEPTION: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 257161150-1155570 (-738329331)**

Can someone provide guidance on the issue please ?

Thanks,
Ashish

**Comment by amtrack** [comment]
Hi @kaulonline 
i added some temporary logging on the `debug-listing-metadata` branch.

Can you please install the given version and re-run the command with `DEBUG=force-dev-tool` prefixed?

```console
npm install -g git+https://github.com/amtrack/force-dev-tool.git#debug-listing-metadata
```

```console
DEBUG=force-dev-tool force-dev-tool fetch --progress
```

**Comment by marsson** [comment]
Hey Guys,
I took the liberty to look into this issue as it was affecting me too.
What i found out is that StandardValueSetTranslation was giving an error when being retrieved.
The solution I had for the issue, was to remove it from the metadataTypeNames array as follows on the describe-remote.js:

`var metadataTypeNames = _.pluck(self.describeMetadataResult.metadataObjects, 'xmlName');
			metadataTypeNames = _.without(_.flatten(metadataTypeNames), 'StandardValueSetTranslation');`

Best Regards!

**Comment by amtrack** [comment]
@marsson 
I'm glad you were able to determine the offending Metadata Type.

As an alternative to programmatically removing it, you should also be able to achieve that using the `.forceignore` approach.
In this case you would need to create a `.forceignore` file containing

```text
StandardValueSetTranslation/*
```

and then run force-dev-tool using

```console
$ force-dev-tool fetch --use-forceignore
```

However the question remains why fetching the `StandardValueSetTranslation` Metadata info fails in your org. I found the following on stackexchange, which might describe your issue: [StandardValueSetTranslation retrieval yields an UNKNOWN_EXCEPTION](https://salesforce.stackexchange.com/questions/156511/standardvaluesettranslation-retrieval-yields-an-unknown-exception)

**Comment by kaulonline** [comment]
Hey Guys, 
Thanks for your response..

Unfortunately I am still unable to get the erroneous component type causing this behavior
`metadata.list(): [{"type":"StaticResource"},{"type":"Scontrol"},{"type":"Certificate"}]
metadata.list(): [{"type":"AuraDefinitionBundle"},{"type":"LightningComponentBundle"},{"type":"ApexComponent"}]
metadata.list(): [{"type":"ApexPage"},{"type":"ServiceChannel"},{"type":"QueueRoutingConfig"}]
metadata.list(): [{"type":"ServicePresenceStatus"},{"type":"PresenceUserConfig"},{"type":"Queue"}]
metadata.list(): [{"type":"CaseSubjectParticle"},{"type":"ExternalDataSource"},{"type":"NamedCredential"}]
metadata.list(): [{"type":"ExternalServiceRegistration"},{"type":"Role"},{"type":"Group"}]
metadata.list(): [{"type":"GlobalValueSet"},{"type":"StandardValueSet"},{"type":"CustomPermission"}]
metadata.list(): [{"type":"CustomObject"},{"type":"ReportType"},{"type":"Report"}]
metadata.list(): [{"type":"Dashboard"},{"type":"AnalyticSnapshot"},{"type":"CustomFeedFilter"}]
metadata.list(): [{"type":"Layout"},{"type":"Document"},{"type":"CustomPageWebLink"}]
metadata.list(): [{"type":"Letterhead"},{"type":"EmailTemplate"},{"type":"QuickAction"}]
metadata.list(): [{"type":"FlexiPage"},{"type":"CustomTab"},{"type":"CustomApplicationComponent"}]
metadata.list(): [{"type":"CustomApplication"},{"type":"Portal"},{"type":"EmbeddedServiceConfig"}]
metadata.list(): [{"type":"EmbeddedServiceLiveAgent"},{"type":"EmbeddedServiceBranding"},{"type":"Flow"}]
metadata.list(): [{"type":"FlowDefinition"},{"type":"EventSubscription"},{"type":"EventDelivery"}]
metadata.list(): [{"type":"Workflow"},{"type":"AssignmentRules"},{"type":"AutoResponseRules"}]
metadata.list(): [{"type":"EscalationRules"},{"type":"PostTemplate"},{"type":"ApprovalProcess"}]
metadata.list(): [{"type":"HomePageComponent"},{"type":"HomePageLayout"},{"type":"CustomObjectTranslation"}]
metadata.list(): [{"type":"Translations"},{"type":"GlobalValueSetTranslation"},{"type":"StandardValueSetTranslation"}]
metadata.list(): [{"type":"ApexClass"},{"type":"ApexTrigger"},{"type":"ApexTestSuite"}]
metadata.list(): [{"type":"Profile"},{"type":"PermissionSet"},{"type":"CustomMetadata"}]
metadata.list(): [{"type":"ProfilePasswordPolicy"},{"type":"ProfileSessionSetting"},{"type":"DataCategoryGroup"}]
metadata.list(): [{"type":"RemoteSiteSetting"},{"type":"CspTrustedSite"},{"type":"MatchingRules"}]
metadata.list(): [{"type":"DuplicateRule"},{"type":"CleanDataService"},{"type":"AuthProvider"}]
metadata.list(): [{"type":"EclairGeoData"},{"type":"CustomSite"},{"type":"ChannelLayout"}]
metadata.list(): [{"type":"ContentAsset"},{"type":"SharingRules"},{"type":"SharingSet"}]
metadata.list(): [{"type":"Community"},{"type":"ChatterExtension"},{"type":"CallCenter"}]
metadata.list(): [{"type":"MilestoneType"},{"type":"EntitlementProcess"},{"type":"EntitlementTemplate"}]
metadata.list(): [{"type":"ConnectedApp"},{"type":"AppMenu"},{"type":"DelegateGroup"}]
metadata.list(): [{"type":"SiteDotCom"},{"type":"Network"},{"type":"NetworkBranding"}]
metadata.list(): [{"type":"CommunityThemeDefinition"},{"type":"BrandingSet"},{"type":"CommunityTemplateDefinition"}]
metadata.list(): [{"type":"FlowCategory"},{"type":"LightningBolt"},{"type":"LightningExperienceTheme"}]
metadata.list(): [{"type":"ManagedTopics"},{"type":"KeywordList"},{"type":"UserCriteria"}]
metadata.list(): [{"type":"ModerationRule"},{"type":"SamlSsoConfig"},{"type":"CorsWhitelistOrigin"}]
metadata.list(): [{"type":"ActionLinkGroupTemplate"},{"type":"TransactionSecurityPolicy"},{"type":"Skill"}]
metadata.list(): [{"type":"LiveChatDeployment"},{"type":"LiveChatButton"},{"type":"LiveChatAgentConfig"}]
metadata.list(): [{"type":"SynonymDictionary"},{"type":"PathAssistant"},{"type":"LeadConvertSettings"}]
metadata.list(): [{"type":"LiveChatSensitiveDataRule"},{"type":"PlatformCachePartition"},{"type":"TopicsForObjects"}]
metadata.list(): [{"type":"EmailServicesFunction"},{"type":"Settings"},{"type":"CustomLabel"}]
metadata.list(): [{"type":"CustomField"},{"type":"Index"},{"type":"BusinessProcess"}]
metadata.list(): [{"type":"CompactLayout"},{"type":"RecordType"},{"type":"WebLink"}]
metadata.list(): [{"type":"ValidationRule"},{"type":"SharingReason"},{"type":"ListView"}]
metadata.list(): [{"type":"FieldSet"},{"type":"WorkflowFieldUpdate"},{"type":"WorkflowKnowledgePublish"}]
metadata.list(): [{"type":"WorkflowTask"},{"type":"WorkflowAlert"},{"type":"WorkflowSend"}]
metadata.list(): [{"type":"WorkflowOutboundMessage"},{"type":"WorkflowRule"},{"type":"AssignmentRule"}]
metadata.list(): [{"type":"AutoResponseRule"},{"type":"EscalationRule"},{"type":"MatchingRule"}]
metadata.list(): [{"type":"SharingOwnerRule"},{"type":"SharingCriteriaRule"}]
Error: [mydev]: sf:UNKNOWN_EXCEPTION: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 462760110-2264582 (-738329331)

`

**Comment by amtrack** [comment]
@kaulonline given your debug log i would suggest creating a `.forceignore` file containing

```text
SharingOwnerRule/*
SharingCriteriaRule/*`
```

and then run force-dev-tool using

```console
$ force-dev-tool fetch --use-forceignore
```
