### ISSUE TITLE
Delete the deployed components from salesforce

### ISSUE THREAD

**Issue by saranya-gotrala** [amtrack/force-dev-tool#169]
Hi Team,

Can someone help me how to delete the salesforce components with force-dev-tool. if it is with destructive.xml file, then how to use it.

Thanks,
Saranya

**Comment by dieffrei** [comment]
Hi @saranya-gotrala, you just need to make the deploy, the destructive.xml will be processed automatically after create/update components + test phase.

**Comment by saranya-gotrala** [comment]
Hi @dieffrei,

Thanks for immediate response.

May I know the folder structure where to place destructive.xml file and process when it deploy one sandbox to another. 
src--> package.xml and descructive.xml

Thanks,
Saranya

**Comment by amtrack** [comment]
@saranya-gotrala I'm not sure if i understand your question.

Did you already read the README?

I copied the relevant section from the README below. Note that the `desctructiveChanges.xml` file will be generated and placed in the `config/deployments/undo-vat` directory (in this example).

And then you can use the generated directory `config/deployments/undo-vat` to deploy the destructive changes to an org.

```console
$ force-dev-tool deploy -d config/deployments/undo-vat
```

---

**Creating destructive deployments (reverting changes)**

1\. By explicitly listing metadata files or metadata components
```console
$ echo "" | force-dev-tool changeset create undo-vat --destructive src/pages/AccountExtensionVAT.page CustomField/Account.VAT__c
```

2\. By providing a unified diff (e.g. `git diff`)
```console
$ git diff --no-renames feature/vat master | force-dev-tool changeset create undo-vat
```

Both approaches lead to the following result
```console
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
 <version>38.0</version>
</Package>

Destructive Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
 <types>
     <members>Account.VAT__c</members>
     <name>CustomField</name>
 </types>
 <types>
     <members>AccountExtensionVAT</members>
     <name>ApexPage</name>
 </types>
</Package>

exported metadata container to config/deployments/undo-vat
```

**Comment by saranya-gotrala** [comment]
Hi @amtrack ,

Thanks for response.

I am trying to do CI/CD with GitLab, as I have gone through the README file and followed the same in YAML file but I don't see any descrutive.xml or folder structure created. please find the images attached. 
![image](https://user-images.githubusercontent.com/23525621/46797772-1469ef80-cd1e-11e8-9d4f-ccd9e719aaa4.png)
![image](https://user-images.githubusercontent.com/23525621/46797820-35cadb80-cd1e-11e8-9b21-fea713878f88.png)

I have a question like do I need to create the changeset each and every time or is there any possibility to modify existing one? how to delete custom labels 
   ex: Lets say there are three developers wants to delete three different components, can they use the same changeset for deployment for three components? 

Thanks,
Saranya

**Comment by amtrack** [comment]
@saranya-gotrala 
It seems to me that your questions go far beyond the original issue of "deleting metadata with force-dev-tool".

If you would like to be consulted on how to do CI/CD with Salesforce and talk about your specific demands, I'm available for freelance work - please send me an [e-mail](mailto:mr.amtrack@gmail.com).
