### ISSUE TITLE
Force-dev-tool is not able to retrieve the dashboard components from unfiled$public folder.

### ISSUE THREAD

**Issue by 92SGupta** [amtrack/force-dev-tool#180]
I am trying to fetch the Dashboard components from the source org using the below package.xml but it seems the force-dev-tool is not able to fetch the dashboard components and reports from the unfiled$public folder. Is it because of any limitations to the force-dev-tool?

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AgentDashboards</members>
        <members>FoldersDashboard</members>
        <members>Sample_Reports_For_Dashboards</members>
        <name>PLACEHOLDER</name>
    </types>
    <types>
        <members>Account Receivables Team</members>
        <members>Admin</members>
        <members>Advisor</members>
        <members>Channel Manager</members>
        <members>Collections Agent</members>
        <members>Collections Back Office Agent</members>
        <members>Commercial Manager</members>
        <members>Content Manager</members>
        <members>Content Team Member</members>
        <name>Profile</name>
    </types>
    <types>
        <members>Sample_Reports.Top_10_Cases_by_Age_Account</members>
        <members>unfiled$public.Agent_MyCases</members>
        <members>unfiled$public.Agent_MyCasesbySLA</members>
        <members>unfiled$public.Agent_Top10CasesbyAge</members>
        <name>Report</name>
    </types>
    <version>41.0</version>
</Package>

When i try to retrieve the data i get below error:
{"fileName":"package.xml","problem":"Entity type: 'PLACEHOLDER' is unknown"}
Succeeded
 and it just fetches one report which is Sample_Reports_For_Dashboards.

**Comment by amtrack** [comment]
@92SGupta the delimiter between folder name and file name should be a slash (`/`):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AgentDashboards</members>
        <members>FoldersDashboard</members>
        <members>Sample_Reports_For_Dashboards</members>
        <name>PLACEHOLDER</name>
    </types>
    <types>
        <members>Account Receivables Team</members>
        <members>Admin</members>
        <members>Advisor</members>
        <members>Channel Manager</members>
        <members>Collections Agent</members>
        <members>Collections Back Office Agent</members>
        <members>Commercial Manager</members>
        <members>Content Manager</members>
        <members>Content Team Member</members>
        <name>Profile</name>
    </types>
    <types>
        <members>Sample_Reports/Top_10_Cases_by_Age_Account</members>
        <members>unfiled$public/Agent_MyCases</members>
        <members>unfiled$public/Agent_MyCasesbySLA</members>
        <members>unfiled$public/Agent_Top10CasesbyAge</members>
        <name>Report</name>
    </types>
    <version>41.0</version>
</Package>
```

**Comment by 92SGupta** [comment]
Thanks @amtrack for the help.. change in the delimiter to slash(/) works fine. Please ignore the PLACEHOLDER metadata type as it came because of the config issue which i have corrected now and the correct Metadata type is Dashboard. Now i am able to fetch the data but force-dev-tool is still throwing an error which i am not sure of as what its related to.

Error: ENOENT: no such file or directory, unlink 'unpackaged.zip'

Regards,
Shubham

**Comment by amtrack** [comment]
@92SGupta Please post your command.

**Comment by 92SGupta** [comment]
@amtrack : Please check below. This fetches the data but also gives the error. I have also attached the new package.xml.

force-dev-tool retrieve -d Item-08145_vlocityb02/src vlocityb02
Retrieving from remote vlocityb02 to directory .
Error: ENOENT: no such file or directory, unlink 'unpackaged.zip'

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AgentDashboards</members>
        <members>FoldersDashboard</members>
        <name>Dashboard</name>
    </types>
    <types>
        <members>Account Receivables Team</members>
        <members>Admin</members>
        <members>Advisor</members>
        <members>Channel Manager</members>
        <members>Collections Agent</members>
        <members>Collections Back Office Agent</members>
        <members>Commercial Manager</members>
        <members>Content Manager</members>
        <members>Content Team Member</members>
        <name>Profile</name>
    </types>
    <types>
        <members>Sample_Reports/Top_10_Cases_by_Age_Account</members>
        <members>unfiled$public/Agent_MyCases</members>
        <members>unfiled$public/Agent_MyCasesbySLA</members>
        <members>unfiled$public/Agent_Top10CasesbyAge</members>
        <name>Report</name>
    </types>
    <version>41.0</version>
</Package>

**Comment by 92SGupta** [comment]
@amtrack : Please check below. This fetches the data but also gives the error. I have also attached the new package.xml.

force-dev-tool retrieve -d Item-08145_vlocityb02/src vlocityb02
Retrieving from remote vlocityb02 to directory .
Error: ENOENT: no such file or directory, unlink 'unpackaged.zip'

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AgentDashboards</members>
        <members>FoldersDashboard</members>
        <name>Dashboard</name>
    </types>
    <types>
        <members>Account Receivables Team</members>
        <members>Admin</members>
        <members>Advisor</members>
        <members>Channel Manager</members>
        <members>Collections Agent</members>
        <members>Collections Back Office Agent</members>
        <members>Commercial Manager</members>
        <members>Content Manager</members>
        <members>Content Team Member</members>
        <name>Profile</name>
    </types>
    <types>
        <members>Sample_Reports/Top_10_Cases_by_Age_Account</members>
        <members>unfiled$public/Agent_MyCases</members>
        <members>unfiled$public/Agent_MyCasesbySLA</members>
        <members>unfiled$public/Agent_Top10CasesbyAge</members>
        <name>Report</name>
    </types>
    <version>41.0</version>
</Package>

**Comment by 92SGupta** [comment]
@amtrack  Regarding the usage of slash as delimiter... Is it required only for Report metadata type? Because for Metadata type as Apex classes and objects dot(.) works fine as <parent component.component name>?

**Comment by 92SGupta** [comment]
The error has gone, i am not sure how. Also i got the slash usage as delimiter for the specific metadata type. Closing the Issue now. Thanks for the help!!!!

**Comment by 92SGupta** [comment]
@amtrack Hi , I was able to fetch the components successfully but when i am trying to deploy those using the parent folder / report name i am getting error during validations. Please check below and suggest?

`force-dev-tool validate -d /appdata01/jenkins-slave/workspace/Corm-Vlocity-Feature-Validate1/config/deployments/Item-08328
Running Validation of directory  to remote citc
Error: Validation failed.
 - Error in Report component 'Sample_Reports_For_Dashboards/Agent_MyCasesbySLA': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/Agent_MyCases': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/my_teams_cases_SLA': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/my_team_cases': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/Agent_Top10CasesbyAge': Cannot find folder:Sample_Reports_For_Dashboards
`

My package.xml looks like :

    <types>
        <members>Sample_Reports_For_Dashboards/Agent_MyCases</members>
        <members>Sample_Reports_For_Dashboards/Agent_MyCasesbySLA</members>
        <members>Sample_Reports_For_Dashboards/Agent_Top10CasesbyAge</members>
        <members>Sample_Reports_For_Dashboards/my_team_cases</members>
        <members>Sample_Reports_For_Dashboards/my_teams_cases_SLA</members>
        <name>Report</name>
    </types>
    <version>41.0</version>
</Package>

**Comment by amtrack** [comment]
@92SGupta To retrieve and deploy the folder itself, see below
(Note: this does not work for the reserved standard folder `unfiled$public`).

```xml
<types>
    <members>Sample_Reports_For_Dashboards</members>
    <members>Sample_Reports_For_Dashboards/Agent_MyCases</members>
    <members>Sample_Reports_For_Dashboards/Agent_MyCasesbySLA</members>
    <members>Sample_Reports_For_Dashboards/Agent_Top10CasesbyAge</members>
    <members>Sample_Reports_For_Dashboards/my_team_cases</members>
    <members>Sample_Reports_For_Dashboards/my_teams_cases_SLA</members>
    <name>Report</name>
</types>
<version>41.0</version>
```

**Comment by 92SGupta** [comment]
@amtrack  thanks for the quick response . I tried the same and still got the same error. I fetched the reports from unfiled$public and Sample_Reports_For_Dashboards . And they all came under the same folder Sample_Reports_For_Dashboards. Please see below

[jenkins@rb-dv-dpvmjks02 Item-08328]$ ls -lrt
total 8
drwxr-xr-x. 2 jenkins developer   43 Apr 24 10:46 dashboards
drwxr-xr-x. 2 jenkins developer 4096 Apr 24 10:47 profiles
drwxr-xr-x. 2 jenkins developer  152 Apr 24 11:36 objects
drwxr-xr-x. 3 jenkins developer   43 Apr 24 12:44 reports
-rw-r--r--. 1 jenkins developer 2590 Apr 24 13:01 package.xml
[jenkins@rb-dv-dpvmjks02 Item-08328]$
[jenkins@rb-dv-dpvmjks02 Item-08328]$
[jenkins@rb-dv-dpvmjks02 Item-08328]$ vi package.xml
[jenkins@rb-dv-dpvmjks02 Item-08328]$
[jenkins@rb-dv-dpvmjks02 Item-08328]$
[jenkins@rb-dv-dpvmjks02 Item-08328]$ cd reports/
[jenkins@rb-dv-dpvmjks02 reports]$ ls
Sample_Reports_For_Dashboards
[jenkins@rb-dv-dpvmjks02 reports]$ cd Sample_Reports_For_Dashboards/
[jenkins@rb-dv-dpvmjks02 Sample_Reports_For_Dashboards]$ ls
Agent_MyCasesbySLA.report  Agent_MyCases.report  Agent_Top10CasesbyAge.report  my_team_cases.report  my_teams_cases_SLA.report
[jenkins@rb-dv-dpvmjks02 Sample_Reports_For_Dashboards]$
[jenkins@rb-dv-dpvmjks02 Sample_Reports_For_Dashboards]$
[jenkins@rb-dv-dpvmjks02 Sample_Reports_For_Dashboards]$
[jenkins@rb-dv-dpvmjks02 Sample_Reports_For_Dashboards]$ force-dev-tool validate -d /appdata01/jenkins-slave/workspace/Corm-Vlocity-Feature-Validate1/config/deployments/Item-08328
Running Validation of directory ../.. to remote citc
Error: Validation failed.
 - Error in Report component 'Sample_Reports_For_Dashboards/Agent_MyCases': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/Agent_MyCasesbySLA': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/Agent_Top10CasesbyAge': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/my_team_cases': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/my_teams_cases_SLA': Cannot find folder:Sample_Reports_For_Dashboards

jenkins@rb-dv-dpvmjks02 Sample_Reports_For_Dashboards]$ less ../../package.xml
<types>
        <members>Sample_Reports_For_Dashboards</members>
        <members>Sample_Reports_For_Dashboards/Agent_MyCases</members>
        <members>Sample_Reports_For_Dashboards/Agent_MyCasesbySLA</members>
        <members>Sample_Reports_For_Dashboards/Agent_Top10CasesbyAge</members>
        <members>Sample_Reports_For_Dashboards/H3g_my_team_cases</members>
        <members>Sample_Reports_For_Dashboards/my_teams_cases_SLA</members>
        <name>Report</name>
    </types>
    <version>41.0</version>
</Package>

**Comment by 92SGupta** [comment]
@amtrack I got the issue, it was because my target org didn't had the folder Sample_Reports_For_Dashboards already created hence the validation was failing. I have created it now and now the validation and deployment both are successful. Is there any way i can automatically create the parent folder first and then deploy the code?

**Comment by amtrack** [comment]
It is sufficient to deploy folders and reports together. No need to do a pre-deploy.
Please see my last example I gave you.

**Comment by 92SGupta** [comment]
@amtrack Sorry but i have already tried that and both validation and deploy  fails with same error. Please check below:

force-dev-tool deploy -d /appdata01/jenkins-slave/workspace/Corm-Vlocity-Feature-Validate1/config/deployments/Item-08372
Running Deployment of directory  to remote validation
Error: Deployment failed.
 - Error in Report component 'Sample_Reports_For_Dashboards/my_team_cases': Cannot find folder:Sample_Reports_For_Dashboards
 - Error in Report component 'Sample_Reports_For_Dashboards/my_teams_cases_SLA': Cannot find folder:Sample_Reports_For_Dashboards


`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Sample_Reports_For_Dashboards</members>
        <members>Sample_Reports_For_Dashboards/my_team_cases</members>
        <members>Sample_Reports_For_Dashboards/my_teams_cases_SLA</members>
        <name>Report</name>
    </types>
    <version>41.0</version>
</Package>`

**Comment by amtrack** [comment]
And make sure you really retrieve the Metadata using that package.xml first (including the folder).

**Comment by 92SGupta** [comment]
@amtrack  I am sorry .. I got it now. Thanks

**Comment by 92SGupta** [comment]
> And make sure you really retrieve the Metadata using that package.xml first (including the folder).

@amtrack   Yeah i was making this mistake and now i got it . I am now able to validate and deploy successfully. You are really helpful mate , thanks a ton!!!!
