### ISSUE TITLE
Lightning Web Components isn't supported by force-dev-tool

### ISSUE THREAD

**Issue by abhisheksaxena7** [amtrack/force-dev-tool#181]
We use Force-dev-tool to deploy metadata to orgs but when we add LWC in the mix, it doesn't seem to pick them up, put them in package.xml and deploy them. Can we expect a fix regarding LWC's soon?

**Comment by sheldonleelazarus** [comment]
@amtrack this would be very helpful if LWC is added to the force-dev-tool.. please....

**Comment by amtrack** [comment]
@abhisheksaxena7 please see #198 by @sheldonleelazarus

**Comment by abd3** [comment]
@amtrack, see, people still love your project

**Comment by abhisheksaxena7** [comment]
Wonderful!! Will try it out and let you know.
