### ISSUE TITLE
Support to CustomNotificationType

### ISSUE THREAD

**Issue by froucher** [amtrack/force-dev-tool#211]
Hello,

Recently we have created a delta with a CustomNotificationType metadata and the delta has not generated this new metadata, CustomNotificationType are available in API version 46.0 and later.

Reference: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_customnotificationtype.htm

If you want, I can try to create a Pull Request with this new feature...

Regards

**Comment by amtrack** [comment]
addressed in #213
