### ISSUE TITLE
"customSettingAccesses" changes in Profile xml file are not getting picked in the pipelines. 

### ISSUE THREAD

**Issue by nitssnatha** [amtrack/force-dev-tool#218]
Hi @amtrack 
When I am adding custom setting permissions to profile file as per version 47. Its not getting validated against org.

**Comment by amtrack** [comment]
@nitssnatha Can you please provide more information about what you are trying to do?

I have no insight what you are doing _in the pipelines_ ...

**Comment by nitssnatha** [comment]
I am just deploying a profile with some custom setting in "customSettingAccesses" tag which is not getting validated against the target org. 
For eg: 
   <customSettingAccesses>
        <enabled>true</enabled>
        <name>CustomSetting__c</name>   //API name of custom setting. 
    </customSettingAccesses>

**Comment by amtrack** [comment]
@nitssnatha According to the Salesforce Metadata docs ([v47](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_profile.htm) and [v48](https://developer.salesforce.com/docs/atlas.en-us.224.0.api_meta.meta/api_meta/meta_profile.htm)) `customSettingAccesses` is only available with API version 48.

**Comment by amtrack** [comment]
@nitssnatha @joshnarani I've just tested this and can now confirm that this is indeed a bug.

**Comment by nitssnatha** [comment]
Thanks, @amtrack  for testing this.
