### ISSUE TITLE
Can I customize the package as per the sfdx folder structure

### ISSUE THREAD

**Issue by Saranyagotraladevops** [amtrack/force-dev-tool#231]
As per the force-dev-tool, src/package.xml folder structure. Now for sfdx cli it is like force-dev-tool/ and manifest/ folder structure.
Is it possible for me to customize force-dev-tool to sfdx cli folder. 
I need this change to be applicable on change set creation.
Please suggest.

**Comment by amtrack** [comment]
@Saranyagotraladevops What are you trying to do with force-dev-tool?

Note: force-dev-tool only works for Metadata in the traditional (composed) format.
It doesn't work with the uncomposed SFDX source format of Metadata.

Per convention force-dev-tool uses the `src` directory.
However if you want to retrieve or deploy another Metadata folder (in traditional format) you can specify the folder

```console
force-dev-tool retrieve -d myothermetadatafolder
force-dev-tool deploy -d myothermetadatafolder
```

**Comment by Saranyagotraladevops** [comment]
Thanks for coming back on this.
