### ISSUE TITLE
Recordtype Issue

### ISSUE THREAD

**Issue by sheldonleelazarus** [amtrack/force-dev-tool#233]
Hi All

I am using Azure DevOps to deploy my changes to different sandboxes , Azure DevOps uses Linux agents, for the past few months i started getting the below errors:

 Error in RecordType component 'Case.CCC_Angola': At least one value is required to create this picklist.
Error in RecordType component 'Contact.Inactive_Client_Contact_Record_Type': At least one value is required to create this picklist.

These errors occurred even though i made no changes to the recordtypes at all or anything related to these recordtypes, I first thought that the diff was not working but then when i ran a deployment from my machine the diff did not pick recordtype changes and everything could be deployed correctly

Is there something i am missing?

**Comment by amtrack** [comment]
@sheldonleelazarus It would be great if you could provide more context on about what you are trying to do.

- What commands are you running for the deployment?
- What do the commands print as output?
- Can you provide an (anonymized) diff?

**Comment by sheldonleelazarus** [comment]
Hi @amtrack 

- I am doing a git diff of branches (commands I am using) - **git diff  qa feature/US-12 | force-dev-tool changeset create Package**
- I have attached the log of the failed deployment, in the log you will see the package.xml that is being created shows Case.CCC_Angola recordtype being deployed however no changes were made to this recordtype but the recordtype that should be deployed is Case.Cross_Border_CoE_Closed_Record_Type which is not in the package.xml which causes the deployment to fail because it suppose to be in the package.xml
[tasklog_7.log](https://github.com/amtrack/force-dev-tool/files/4608389/tasklog_7.log)

- I then ran the same command on my local machine and the package.xml shows the correct output with the correct recordtype being deployed
[package.log](https://github.com/amtrack/force-dev-tool/files/4608436/package.log)

**Comment by amtrack** [comment]
@sheldonleelazarus Are you saying that it works on your machine but not on Azure DevOps?

The git command only works when both branches are checked out:
I can imagine that this is the case on your machine but maybe not on Azure DevOps.

Please verify on Azure DevOps that the following command works before piping it to force-dev-tool:

```console
git diff qa feature/US-12
````

If this doesn't output the desired result, you can try to diff the remote branches.

```console
git diff origin/qa origin/feature/US-12
```

**Comment by sheldonleelazarus** [comment]
@amtrack  Yes my commands worked before, this bug started happening from about Feb for me and I can confirm I am actually using git diff origin/qa origin/feature/US-12 in Azure DevOps

**Comment by amtrack** [comment]
@sheldonleelazarus It's hard for me to believe that force-dev-tool picks up a different RecordType which is not in the diff and that this only happens in Azure DevOps?!

Can you please output `git diff origin/qa origin/feature/US-12` right before doing `git diff origin/qa origin/feature/US-12 | force-dev-tool changeset create Package`, so that we're 100% sure the diff is the right one to pipe into force-dev-tool?

**Comment by amtrack** [comment]
@sheldonleelazarus any news on this?

**Comment by sheldonleelazarus** [comment]
@amtrack  yes, i tried to use a different repo to perform similar changes and i could not replicate the issue with Azure DevOps, everything worked as expected, I have a suspicion it could be the metadata file or the type of IDE that was used to update the metadata in our repo

**Comment by amtrack** [comment]
@sheldonleelazarus OK, good to know. Thanks for the feedback!
