### ISSUE TITLE
How to validate a only package changes created with changeset

### ISSUE THREAD

**Issue by Saranyagotraladevops** [amtrack/force-dev-tool#237]
I am unable to use following commands which i have seen in one of the websites mentioned below.
https://devhub.io/repos/amtrack-force-dev-tool

$ force-dev-tool validateTest -d config/deployments/vat

Kindly guide me.

**Comment by amtrack** [comment]
```console
force-dev-tool deploy -c -d config/deployments/vat
```

If you need other options see `force-dev-tool deploy -h` for help.
