### ISSUE TITLE
Version 2.8.0 vs 2.7.0

### ISSUE THREAD

**Issue by froucher** [amtrack/force-dev-tool#255]
Hi @amtrack,

I am checking the last version (`2.8.0`) of force-dev-tool, and I have a weird issue.

The issue is that `package.xml` with `2.8.0` has a lot of less elements that the `package.xml` generate with `2.7.0` version and when I execute the `changeset create delta` with `2.8.0` the console shows a lot of lines like:

```sh
readable not null
readable not null
readable not null
readable not null
readable not null
readable not null
readable not null
readable not null
readable not null
readable not null
readable not null
readable not null
....
```

It is weird because the changeset is created without `ApexClass`, `ApexPage`, `ApexTrigger`, `Compact Layout`, and many others metadata that are currently supported.

![image](https://user-images.githubusercontent.com/8971151/88082457-16631280-cb82-11ea-95bf-efb3152b12d4.png)

I updated my local node version to `12` but the issue continues, and when I launch functional tests it is all green.

I am going to continue investigating why it is happening.., but any idea of why it is happening is welcome.

Thanks.

**Comment by amtrack** [comment]
@froucher hmm, maybe there is a mismatch between the build for development/testing and the production build?
Are you able to reproduce this using a build from latest master branch? (git clone; npm link)

**Comment by froucher** [comment]
Yes, I also reproduce the issue with master branch, it seems the issue started with the version 2.7.1, maybe it is a npm dependency issue, I think I am close to find why it is happening...

**Comment by froucher** [comment]
It seems the issue starts with this commit: 0a9cfab

Because I rollbacked commits one by one until the previous commit fbca8bd, redo the npm install for "event-stream" old dependency, and it started to work again.

And if I move my local again to 0a9cfab commit and redo the npm install, then the issue comes back.

I will continue to investigate why "merge-stream" dependency is not working.

**Comment by amtrack** [comment]
@froucher Can you please the [fix/parse-input](https://github.com/amtrack/force-dev-tool/tree/fix/parse-input) this branch?

**Comment by froucher** [comment]
This fix is working fine!! 👏 👏 👏 

There's no difference between both package.xml
