### ISSUE TITLE
Changes in profile metadata files are not included in changeset

### ISSUE THREAD

**Issue by papariz** [amtrack/force-dev-tool#84]
Produced in v 0.13.0.  Changes to profile metadata files are not added to manifest and src folder when the changeset is created with git diff master | force-dev-tool changeset create build. Changes to certain parts of the file do not register as a change to the force-dev-tool including objectPermissions.
<img width="839" alt="screen shot 2017-03-03 at 11 39 09 am" src="https://cloud.githubusercontent.com/assets/26151425/23559766/147ddd06-0006-11e7-8e9b-557bd4c4e736.png">
<img width="567" alt="screen shot 2017-03-03 at 11 38 04 am" src="https://cloud.githubusercontent.com/assets/26151425/23559765/147d3c70-0006-11e7-875a-10dae62439fb.png">

**Comment by amtrack** [comment]
Hi @papariz 

thanks for reporting.
I just tried to reproduce but in my first attempt it just worked.

Is it possible for you to share your git repository with me, so that i can do some investigations?

**Comment by papariz** [comment]
Unfortunately our repo is not publicly accessible. If you've tested all the tags in the  profile xml then maybe I'm doing something wrong.

**Comment by papariz** [comment]
@amtrack I believe this was due to the way I was calling git diff. Once I actually committed the changes to the branch, it then registered. Sorry for the confusion.

**Comment by amtrack** [comment]
No worries!
I'm happy that you got it working now :-)

In fact not all parts of the Profile are supported for `force-dev-tool changeset create`, only the most common things like `classAccesses`, `pageAccesses`, `objectPermissions`, `fieldPermissions`, ... (see [here](https://github.com/amtrack/force-dev-tool/blob/f6dc4d3499ecfdd7c8d429fac8a42ff961b1198d/lib/describe-metadata-service.js#L192-L245)).

**Comment by papariz** [comment]
Interesting good to know. Hopefully we won't hit on anything that is unsupported.
