### ISSUE TITLE
npm install hanging on loadDep:xmldoc

### ISSUE THREAD

**Issue by GeneralDoddi** [amtrack/force-dev-tool#91]
I am trying to install the package on Ubuntu 16.04

The install hangs on loadDep:xmldoc after 33% of the install

Silly log: 

npm verb addNamed "2.4.2" is a plain semver version for yazl
npm sill cache afterAdd docopt@0.6.2
npm verb afterAdd /home/ubuntu/.npm/docopt/0.6.2/package/package.json not in flight; writing
npm sill cache afterAdd multimatch@2.1.0
npm verb afterAdd /home/ubuntu/.npm/multimatch/2.1.0/package/package.json not in flight; writing
npm sill cache afterAdd tabtab@0.0.4
npm verb afterAdd /home/ubuntu/.npm/tabtab/0.0.4/package/package.json not in flight; writing
npm sill cache afterAdd glob@7.1.2
npm verb afterAdd /home/ubuntu/.npm/glob/7.1.2/package/package.json not in flight; writing
npm sill cache afterAdd vinyl-fs@2.4.4
npm verb afterAdd /home/ubuntu/.npm/vinyl-fs/2.4.4/package/package.json not in flight; writing
npm sill cache afterAdd async@2.4.1
npm verb afterAdd /home/ubuntu/.npm/async/2.4.1/package/package.json not in flight; writing
npm sill cache afterAdd yauzl@2.8.0
npm verb afterAdd /home/ubuntu/.npm/yauzl/2.8.0/package/package.json not in flight; writing
npm sill cache afterAdd xml2js@0.4.17
npm verb afterAdd /home/ubuntu/.npm/xml2js/0.4.17/package/package.json not in flight; writing
npm sill cache afterAdd tmp@0.0.28
npm verb afterAdd /home/ubuntu/.npm/tmp/0.0.28/package/package.json not in flight; writing
npm sill cache afterAdd chalk@1.1.3
npm verb afterAdd /home/ubuntu/.npm/chalk/1.1.3/package/package.json not in flight; writing
npm sill cache afterAdd vinyl@1.2.0
npm verb afterAdd /home/ubuntu/.npm/vinyl/1.2.0/package/package.json not in flight; writing
npm sill cache afterAdd find-up@1.1.2
npm verb afterAdd /home/ubuntu/.npm/find-up/1.1.2/package/package.json not in flight; writing
npm sill cache afterAdd parse-diff@0.3.2
npm verb afterAdd /home/ubuntu/.npm/parse-diff/0.3.2/package/package.json not in flight; writing
npm sill cache afterAdd fs-extra@0.30.0
npm verb afterAdd /home/ubuntu/.npm/fs-extra/0.30.0/package/package.json not in flight; writing
npm sill cache afterAdd underscore@1.8.3
npm verb afterAdd /home/ubuntu/.npm/underscore/1.8.3/package/package.json not in flight; writing
npm sill cache afterAdd yazl@2.4.2
npm verb afterAdd /home/ubuntu/.npm/yazl/2.4.2/package/package.json not in flight; writing
npm sill cache afterAdd mkdirp@0.5.1
npm verb afterAdd /home/ubuntu/.npm/mkdirp/0.5.1/package/package.json not in flight; writing
npm sill cache afterAdd jsforce@1.8.0
npm verb afterAdd /home/ubuntu/.npm/jsforce/1.8.0/package/package.json not in flight; writing
npm verb afterAdd /home/ubuntu/.npm/docopt/0.6.2/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/multimatch/2.1.0/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/tabtab/0.0.4/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/vinyl-fs/2.4.4/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/glob/7.1.2/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/async/2.4.1/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/yauzl/2.8.0/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/tmp/0.0.28/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/xml2js/0.4.17/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/chalk/1.1.3/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/vinyl/1.2.0/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/find-up/1.1.2/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/parse-diff/0.3.2/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/fs-extra/0.30.0/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/underscore/1.8.3/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/yazl/2.4.2/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/mkdirp/0.5.1/package/package.json written
npm verb afterAdd /home/ubuntu/.npm/jsforce/1.8.0/package/package.json written
loadDep:xmldoc            ▀ ╢██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

the log doesn't show me explicitly what it is stopping on, i'm trying to install manually some packages to see if they are causing it, but to no help.

I have already installed it on a OS X and it works fine, but it seems like the package is stalling on Linux for some reason

Is there any way around this ?

-Doddi

**Comment by GeneralDoddi** [comment]
I tried to install on CentOS7 with the same problem

**Comment by amtrack** [comment]
That's strange! Which node/npm version are you running?

**Comment by GeneralDoddi** [comment]
The latest version from the ubuntu package manager (Sorry for not having details I'm out of town) :)

I am using Ubuntu 16.04 cloud edition, my colleague told me He could install on LTE edition on his VM. This is a very odd problem indeed

**Comment by amtrack** [comment]
OK, I will try to bump some package versions (it is time to do this anyway) next week and hope that this will solve this problem. Thanks for reporting!

**Comment by GeneralDoddi** [comment]
I have been trying to fool around on installing, now i spawned a Ubuntu 16.04 LTS myself and didn't get the package installed, i then decided to install all dependencies first and then try the package, 

All dependencies installed fine but the force-dev-tool package still hangs at same place, i hope you can recreate this

**Comment by amtrack** [comment]
@GeneralDoddi Can you try installing using the following command:

```console
$ npm install --global amtrack/force-dev-tool#bump-xmldoc
```

**Comment by GeneralDoddi** [comment]
@amtrack 

ubuntu@jenkins-salesforce-dev:~$ sudo npm install --global amtrack/force-dev-tool#bump-xmldoc --loglevel=silly
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--global',
npm verb cli   'amtrack/force-dev-tool#bump-xmldoc',
npm verb cli   '--loglevel=silly' ]
npm info using npm@3.5.2
npm info using node@v4.2.6
npm sill loadCurrentTree Starting
npm sill install loadCurrentTree
npm sill install readGlobalPackageData
npm sill fetchPackageMetaData amtrack/force-dev-tool#bump-xmldoc
npm sill fetchOtherPackageData amtrack/force-dev-tool#bump-xmldoc
npm sill cache add args [ 'amtrack/force-dev-tool#bump-xmldoc', null ]
npm verb cache add spec amtrack/force-dev-tool#bump-xmldoc
npm sill cache add parsed spec Result {
npm sill cache add   raw: 'amtrack/force-dev-tool#bump-xmldoc',
npm sill cache add   scope: null,
npm sill cache add   name: null,
npm sill cache add   rawSpec: 'amtrack/force-dev-tool#bump-xmldoc',
npm sill cache add   spec: 'github:amtrack/force-dev-tool#bump-xmldoc',
npm sill cache add   type: 'hosted',
npm sill cache add   hosted: 
npm sill cache add    { type: 'github',
npm sill cache add      ssh: 'git@github.com:amtrack/force-dev-tool.git#bump-xmldoc',
npm sill cache add      sshUrl: 'git+ssh://git@github.com/amtrack/force-dev-tool.git#bump-xmldoc',
npm sill cache add      httpsUrl: 'git+https://github.com/amtrack/force-dev-tool.git#bump-xmldoc',
npm sill cache add      gitUrl: 'git://github.com/amtrack/force-dev-tool.git#bump-xmldoc',
npm sill cache add      shortcut: 'github:amtrack/force-dev-tool#bump-xmldoc',
npm sill cache add      directUrl: 'https://raw.githubusercontent.com/amtrack/force-dev-tool/bump-xmldoc/package.json' } }
npm verb addRemoteGit caching amtrack/force-dev-tool#bump-xmldoc
npm verb addRemoteGit amtrack/force-dev-tool#bump-xmldoc is a repository hosted by github
npm sill tryGitProto attempting to clone git://github.com/amtrack/force-dev-tool.git#bump-xmldoc
npm sill tryClone cloning amtrack/force-dev-tool#bump-xmldoc via git://github.com/amtrack/force-dev-tool.git#bump-xmldoc
npm verb tryClone git-github-com-amtrack-force-dev-tool-git-bump-xmldoc-b9a4d58f not in flight; caching
npm info git [ 'clone',
npm info git   '--template=/home/ubuntu/.npm/_git-remotes/_templates',
npm info git   '--mirror',
npm info git   'git://github.com/amtrack/force-dev-tool.git',
npm info git   '/home/ubuntu/.npm/_git-remotes/git-github-com-amtrack-force-dev-tool-git-bump-xmldoc-b9a4d58f' ]
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

it stalls there.

**Comment by GeneralDoddi** [comment]
new development, i noticed it stopped at git://github.com this time and it's common for firewalls to screw with it after switching out the git repo in npm this rolled finally through

git config --global url.https://github.com/.insteadOf git://github.com/

**Comment by amtrack** [comment]
aha, ok.
so this is a firewall issue?

**Comment by GeneralDoddi** [comment]
It looks like it, i must have messed up when i tried the global config change back when i wrote the issue. I've had this problem before at my workplace but the errors were more clear (IE just a plain 500 error for the git page to be unreachable), this one doesn't throw an error at all and just hangs instead

I spawned a fresh instance and fixed the global config and it installed, i'm sorry for taking time from you when this is looking increasingly like a user related problem :(

**Comment by amtrack** [comment]
no worries, i'm glad it works now ;-)
