### ISSUE TITLE
[DOC ENHANCEMENT] - update the doc to provide ways to ignore space difference at eol

### ISSUE THREAD

**Issue by okram999** [amtrack/force-dev-tool#95]
i hope this is a wide spread issue, while doing the git-diff between branches for the package.xml as well as the destructive xml, certains files with just trailing space difference shows up and gets into the XML's. i am using this to avoid files which differ only in space at eol.

`git diff --ignore-space-at-eol master dev | force-dev-tool  changeset create vat `

**Comment by amtrack** [comment]
resolved with f1c52631e9debf3b2b690aeb3e911498aa79fb7f
