### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by okram999** [amtrack/force-dev-tool#96]
@amtrack i got this heap out of memory on my local pc but works on a linux server. My pc have ample system memory. Did you encounter this node.js memory issue? 
Do you have plan to expose the cli, so that user can specify the size as in  https://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory ? 

Finally, i know we spoke about this but do you have any idea on how much of git diff that the cli tool take for generating the changeset? 

thanks

**Comment by amtrack** [comment]
Hi @okram999, sorry for being unresponsive regarding your issues. I cannot guarantee to find time in the near future for development.

I haven't encountered such memory issues yet and don't have any recommended max diff sizes so far.

In general i tend to reimplement relevant and unique parts of force-dev-tool as plugins to the sfdx cli in the future.

The changeset command clearly is such a part. 

At the moment the changeset command lacks support for certain Metadata types and needs to be updated for the PermissionSet behavior new in API version 40.

**Comment by okram999** [comment]
@amtrack , thanks for the response.. Can you let me know, what metadata types are not supported by the changeset command. And also what needs to be updated for the PermissionSet with the new API version 40

**Comment by amtrack** [comment]
PermisssionSets can now be treated as whole files instead of decomposing them into parts: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm

AFAIK own properties of e.g. CustomObject are not yet handled. For example when you only change the description element of a CustomObject.

There might be more.

**Comment by okram999** [comment]
> AFAIK own properties of e.g. CustomObject are not yet handled. For example when you only change the description element of a CustomObject.

this is more like #90 ?

**Comment by amtrack** [comment]
Yes, exactly!

**Comment by okram999** [comment]
btw, the java heap error are rarely seen if use nodejs v8.6.0. May be its due to better GC handling with this version.

**Comment by amtrack** [comment]
Closed by #99
